apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
resources:
- ../../base
- pvc.yaml
configMapGenerator:
- files:
  - application.yml
  name: "82263412-configmap"
patches:
- path: deployment.yaml
- path: ingress.yaml
images:
- name: ce82263412acr.azurecr.io/82263412
  newTag: "202410071108"
